### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by NotHazed** [billsonnn/nitro-react#122]
After 5-10 minutes (maximum 60 minutes) the connection is lost. No error message. You have to reload the client then.

**Comment by dank074** [comment]
> After 5-10 minutes (maximum 60 minutes) the connection is lost. No error message. You have to reload the client then.

does your emulator ping the client? If you are proxying with cf then it is a known issue that they terminate the connection themselves. I think the maximum idle time is 90 seconds

**Comment by NotHazed** [comment]
> > After 5-10 minutes (maximum 60 minutes) the connection is lost. No error message. You have to reload the client then.
> 
> does your emulator ping the client? If you are proxying with cf then it is a known issue that they terminate the connection themselves. I think the maximum idle time is 90 seconds

yes, proxied with cf
what do i need to change to avoid disconnects?

**Comment by dank074** [comment]
> yes, proxied with cf what do i need to change to avoid disconnects?

You need to have your emulator ping the client every 30 seconds or so. That's also a good way of checking for dead connections that haven't been correctly disposed by your emulator (or bots that don't respond back to the ping), so win-win.
