### ISSUE TITLE
Respect bubbles not appearing in Nitro

### ISSUE THREAD

**Issue by NotHazed** [billsonnn/nitro-react#131]
Respect bubbles are not displayed in Nitro for a long time. On my screenshot you can see below the view from the flash client (xx wurde gelobt!) and over there is the Nitro client. There you don't see the respect bubbles.

![image](https://user-images.githubusercontent.com/22569203/211220888-ff0e9211-977e-4e93-ae3b-f844c87d7133.png)

**Comment by dank074** [comment]
make sure your ui-config has these options:

```json
"respect.options": {
        "enabled": false,
        "sound": "sound_respect_received"
    },
```

**Comment by NotHazed** [comment]
Works now, thank you!
