### ISSUE TITLE
furniture does not rotate

### ISSUE THREAD

**Issue by victorlbs** [billsonnn/nitro-react#150]
in the last version the furniture doesn't rotates everything works perfectly except that
![Animação](https://github.com/billsonnn/nitro-react/assets/39808820/bf530136-8333-46a7-b2dc-f9a315d9631d)

**Comment by vanessa** [comment]
Do you see any error on [DevTools](https://developer.chrome.com/docs/devtools/open/) console?

**Comment by dank074** [comment]
You probably finally updated your renderer version. The structure of the furniture json data was changed months ago (maybe close to a year by now)
