### ISSUE TITLE
Add Prettier and revisit some ESLint configs

### ISSUE THREAD

**Issue by vanessa** [billsonnn/nitro-react#159]
I'd like to propose adding [Prettier](https://prettier.io/) to the project, as well as taking some time to revisit the current ESLint configurations in place. I believe that these steps would greatly enhance the codebase and make any contributor's life easier. Here are some thoughts:

- Prettier is like a helper that tidies code automatically, making it consistent and easier to read and understand - everyone can benefit from this, especially when reading code from others
- ESLint with the right configurations can help follow the best coding practices and avoid common mistakes, the proposal to revisit some configs are more related to removing coding style rules that aren't really related to JavaScript/TypeScript conventions - these can be easily handled by prettier
- Any of this formatting can be completely automated in a pre-commit hook ([husky](https://www.npmjs.com/package/husky) + [pretty-quick](https://www.npmjs.com/package/pretty-quick)) so it doesn't add significant overhead to contributors

Would this be useful? I'd be happy to work on it if the maintainers decide to move forward

**Comment by dank074** [comment]
I personally like the idea. 

About the current ESLint rules, @billsonnn is very special about how he wants the code to look, even when it is not the standard formatting for TS/JS projects. This is his project and ultimately any decision made in the past has had to be approved by him, so I am paging him now.
