### ISSUE TITLE
 Client-side Ejectall Modal Does Not Display

### ISSUE THREAD

**Issue by DawnWakening** [billsonnn/nitro-react#94]
When using :ejectall command as per Habbo, the room.confirm.eject_all should display a confirmation message to verify CANCEL or OK to ejecting all the furniture in a room, similarly to :pickall.

Unfortunately, this appears to be missing from Nitro client-side.

**Comment by Snaiker** [comment]
Yes. There's already an merge request for that. I believe soon they will merge it.

**Comment by dank074** [comment]
> Yes. There's already an merge request for that. I believe soon they will merge it.

waiting on bill 😴
